topics = ["core", "fiction", "newspapers", "spoken", "web", "general"]

# Core

core = [
    {
        "voor": "for, in front of",
        "Ik vind het leuk om voor hem te koken": "I like to cook for him",
        "We staan voor de deur van het hotel": "We stand in front of the hotel door",
        "aan": "to",
        "Hij geeft de bloemen aan Lena": "He gives the flowers to Lena",
        "als": "when",
        "Ik krijg dorst als ik die fles zie staan": "I get thirsty when I see that bottle standing there",
        "om": "around",
        "Ik wandelde om het plantsoen": "I walked around the park",
        "nog": "still",
        "Zij is nog jong": "She is still young",
        "bij": "near",
        "Op het pleintje bij de kerk waren kinderen aan het spelen": "Children were playing on the square near the church",
        "uit": "from",
        "Ik kom uit Amsterdam": "I come from Amsterdam",
    },
    {
        "zullen": "will",
        "De filmpjes zullen te zien zijn van het internet": "The videos will be shown on the internet",
        "of": "or",
        "Er reden allang geen trams of auto's meer": "There were no trams or cars running long ago",
        "over": "over, about",
        "Zij klom over het hek": "She climbed over the hedge",
        "Alle informatie over de camping vind je op de website": "All the information about camping is on the website",
        "wel": "rather",
        "Ik vind het wel fijn te horen dat er meer mensen zijn die zich zorgen maken": "I like to hear that more people are concerned",
        "wat": "what",
        "We hebben gedaan wat we moesten doen": "We have done what we had to do",
        "heel": "whole",
        "Sommige mensen fluiten de hele dag": "Some people whistle the whole day",
        "toch": "yet",
        "Ze schold hem uit en toch troostte hij haar": "She scolded him and yet he comforted her",
    },
    {
        "maken": "to make, to repair",
        "Hij maakte een snelle beweging": "He made a fast motion",
        "Hij maakte haar kapotte fiets": "He repaired her broken bicycle",
        "ons": "us, our",
        "Ze kwam naar ons toe": "She came towards us",
        "Een van onze vrienden logeert ergens anders": "One of our friends is staying somewhere else",
        "dan": "than",
        "Daarmee was ze een seconde sneller dan haar oude toptijd": "With it she was a second faster than her previous best time",
        "de mens": "human",
        "Dieren kunnen een innige band met mensen hebben": "Animals can have an intimate bond with humans",
        "alleen": "alone",
        "Hij heeft besloten om alleen te gaan": "He decided to go alone",
        "lang": "long, tall",
        "Het lange meisje kon bij de bovenste plank": "The tall girl could reach the top shelf",
        "Het klonk als een beslissing waarover lang was nagedacht": "It sounded like a decision that had long been considered",
    },
    {
        "af": "off",
        "Hij was me te vlug af": "He was too quick for me",
        "Af en toe zit ik te klappertanden van de kou": "Occasionally my teeth chatter from the cold",
        "mee": "with",
        "Ik heb er ervaring mee": "I have experience with it",
        "enkel": "a few, a single",
        "Na enkele seconden hoorde ik de auto ook": "After a few seconds I also heard the car",
        "toe": "towards",
        "Laura deed spontaan een stap naar hem toe": "Laura took a spontaneous step towards him",
        "volgens": "according to",
        "Het examen aardrijkskunde was volgens de leerlingen te moeilijk": "The geography exam was too hard according to the pupils",
        "vooral": "especially",
        "Ze toonden ons angst en verslagenheid en vooral uitzinnige woede": "They showed us fear and dejection and especially frenzied rage",
        "leggen": "to put",
        "Hij legde het boek op de tafel": "He put the book on the table",
    },
    {
        "alles": "everything",
        "Bij ons in het dorp was alles donker en stil": "Everything was dark and silent near us in the village",
        "even": "just",
        "Hij ging even een biertje drinken in het cafe": "He just went to drink a beer in the pub",
        "vorig": "previous",
        "Het winkelpand stond na het faillissement van het vorige bezitter al geruime tijd leeg": "The shopfront had stood empty for some time after the bankruptcy of the previous owner",
        "gewoon": "usual, normal, easily",
        "In het gewone leven gaat dat anders": "In normal life things are different",
        "Een parkje waar ze allebei gewoon vanuit hun huis naartoe kunnen fietsen": "A park where they both can cycle to easily from their house",
        "halen": "to get (from somewhere), to fetch",
        "Ze weten niet waar ze de formulieren moeten halen": "They don't know where they can get the forms",
        "lijken": "to seem",
        "Het lijkt me erg gezellig om elkaar te zien": "It seems to me very nice to see each other",
        "zetten": "to put (down)",
        "Zij zette de bloemen in een vaas": "She put the flowers in a vase",
    },
    {
        "blijken": "to prove",
        "Dit blijkt uit een eerste rapportage van het onderzoeksbureau": "This is evident from a first report from the research agency",
        "het leven": "life",
        "Er zijn veel kleine conflicten die het dagelijks leven verstoren": "There are many small conflicts which disturb daily life",
        "zo'n": "such a",
        "Ik ben niet zo'n strenge leraar": "I am not such a strict teacher",
        "trekken": "to draw, to pull",
        "Dit evenement trekt ieder jaar veel bezoekers": "This event draws many visitors every year",
        "achter": "behind",
        "Hij gaat weer achter zijn bureau zitten": "He goes to sit behind his desk again",
        "het deel": "part",
        "Er was niemand in dit deel van de stad": "There was no-one in this part of the city",
        "nodig": "necessary",
        "Ze namen de nodige maatregelen": "They took the necessary measures",
        "Voor dit gerecht heeft u ook geroosterde rijst nodig": "You also need roasted rice for this dish",
    },
    {
        "per": "by, per",
        "De paartijvoorzitter wordt per referendum gekozen": "The party leader was chosen by referendum",
        "pas": "only",
        "Leiderschap komt meestal pas tot zijn recht op momenten van crisis": "Leadership usually comes into its own only in moments of crisis",
        "helemaal": "completely",
        "Betty voelde zich niet helemaal op haar gemak": "Betty did not feel completely at ease",
        "het geval": "case",
        "In dat geval moet je het later nog maar eens proberen": "In that case you should try again later",
        "In elk geval is het niet jouw schuld": "In any case it's not your fault",
        "de pad": "toad",
        "weg": "gone",
        "de weg": "road, way",
        "Acht spelers wilden de coach weg hebben": "Eight players wanted the coach gone",
        "eigenlijk": "actually",
        "Els twijfelt, want ze wil eigenlijk niet verhuizen": "Els hesitates because she doesn't actually want to move",
    },
    {
        "eerder": "sooner",
        "Jongeren moeten eerder leren samenwerken dan met elkaar te wedijveren": "Young people must sooner learn to cooperate rather than compete with each other",
        "het paar": "couple, few",
        "Op het nachtkastje staan een paar vergeelde wenskkaarten": "A few yellowed greetings cards are on the bedside table",
        "het moment": "time, moment",
        "Op andere momenten kon ze ook niet trainen": "At other times she couldn't train either",
        "manier": "way, manner",
        "Ik vond een andere manier om je te helpen": "I found another way to help you",
        "zeer": "very (written)",
        "Ze was zeer verzwakt en woog nog 46 kilo": "She was very weakened and still weighed 46 kilos",
        "soms": "sometimes",
        "Soms gaat het niet zoals je wilt": "Sometimes things don't go your way",
        "jammer genoeg": "unfortunately",
        "Jammer genoeg kon ze niet deelnemen aan de wedstrijd": "Unfortunately she could not participate in the match",
        "de poes": "cat",
    },
    {
        "het begin": "start",
        "Er werd een begin gemaakt met hervormingen": "A start was made with reforms",
        "vast": "fixed, certain",
        "Hij heeft wel degelijk een vast inkomen": "He does have a steady income",
        "Zij vindt de maatregelen vast niet streng genoeg": "She probably doesn't think the measures are strict enough",
        "zorgen": "to care, to provide",
        "Een baan zorgt voor status en sociale contacten": "A job provides status and social contacts",
        "meteen": "immediately",
        "Het is niet noodzakelijk om meteen een nieuw toestel te plaatsen": "It is not necessary to immediately install a new appliance",
        "bovendien": "also",
        "Melk is lekker en bovendien gezond": "Milk is tasty and also healthy",
        "graag": "with pleasure",
        "We leerden bij en dat zagen onze ouders en leraren graag": "We were learning and our parents and teachers were pleased to see that",
        "daarna": "afterwards",
        "Het lichte winterse weer lijkt zich komend weekend en waarschijnlijk ook daarna te handhaven": "The light wintery weather seems set to continue the coming weekend and probably beyond",
    },
    {
        "betalen": "to pay",
        "Bovendien betaalt de stad de energiefactuur": "The town also pays the energy bill",
        "de/het soort": "kind of",
        "Ze stond die eerste nacht met haar tentje op een soort dorpsplein": "She stood that first night with her tent on a kind of village square",
        "sluiten": "to close",
        "Het hotel was gesloten van augustus tot april": "The hotel was closed from August to April",
        "de punt": "full stop, point",
        "het punt": "item (abstract)",
        "De zin wordt afgesloten met een punt": "The sentence finishes with a full stop",
        "Het derde punt op de agenda is het feest": "The third item on the agenda is the party",
        "Hij eindigde twee punten achter de leider": "He finished two points behind the leader",
        "raken": "to touch, to hit",
        "In bed zorgde ze ervoor dat haar voeten zijn lichaam niet raakten": "She took care in bed that her feet did not touch his body",
        "stellen": "to put (spoken)",
        "Hij stelt dat het belangrijk is om samen te werken": "He put that it is important to work together",
        "Hij hield niet op met vragen stellen": "He didn't stop asking questions",
    },
    {
        "volledig": "full",
        "Bovendien heerst in ons team volledige openheid": "There is also complete openness in our team",
        "de kater": "tomcat",
        "het feit": "fact",
        "De feiten speelden zich af tussen maart en december": "The facts occured between March and December",
        "de reden": "reason",
        "Een reden voor de scheiding werd niet gegeven": "A reason for the divorce was not given",
        # 8
    },
]

core_vocab = [
    {
        "voor": "for, in front of",
        "aan": "to",
        "als": "when",
        "om": "around",
        "het plantsoen": "park",
        "nog": "still",
        "bij": "near",
        "uit": "from",
    },
    {
        "zullen": "will",
        "of": "or",
        "over": "over, about",
        "wel": "rather",
        "wat": "what",
        "heel": "whole",
        "fluiten": "to whistle",
        "toch": "yet",
        "troosten": "to comfort",
    },
    {
        "maken": "to make, to repair",
        "de beweging": "motion, movement",
        "ons": "us, our",
        "logeren": "to stay, to lodge",
        "dan": "than",
        "de mens": "human",
        "innig": "intimate",
        "alleen": "alone",
        "lang": "long, tall",
    },
    {
        "af": "off",
        "mee": "with",
        "de ervaring": "experience",
        "enkel": "a few, a single",
        "toe": "towards",
        "volgens": "according to",
        "de aardrijkskunde": "geography",
        "leerlingen": "pupils",
        "vooral": "especially",
        "de angst": "fear",
        "de verslagenheid": "dejection",
        "uitzinnig": "frenzied",
        "de woede": "rage",
        "leggen": "to put",
    },
    {
        "alles": "everything",
        "even": "just",
        "vorig": "previous",
        "het winkelpand": "shopfront",
        "het faillissement": "bankruptcy",
        "het bezitter": "owner",
        "gewoon": "usual, normal, easily",
        "halen": "to get (from somewhere), to fetch",
        "lijken": "to seem",
        "zetten": "to put (down)",
    },
    {
        "blijken": "to prove",
        "het leven": "life",
        "verstoren": "to disturb",
        "zo'n": "such a",
        "streng": "strict",
        "trekken": "to draw, to pull",
        "achter": "behind",
        "het deel": "part",
        "nodig": "necessary",
        "de maatregel": "measure",
        "het gerecht": "dish",
    },
    {
        "per": "by, per",
        "pas": "only",
        "helemaal": "completely",
        "het geval": "case",
        "de pad": "toad",
        "weg": "gone",
        "de weg": "road, way",
        "eigenlijk": "actually",
        "twijfelen": "to doubt",
    },
    {
        "eerder": "sooner",
        "wedijveren": "to compete",
        "het paar": "couple, few",
        "het moment": "time, moment",
        "de manier": "way, manner",
        "zeer": "very (written)",
        "soms": "sometimes",
        "jammer genoeg": "unfortunately",
        "de poes": "cat",
    },
    {
        "het begin": "start",
        "de hervorming": "reform",
        "vast": "fixed, certain",
        "degelijk": "sound (adj.)",
        "zorgen": "to care, to provide",
        "meteen": "immediately",
        "het toestel": "appliance",
        "noodzakelijk": "necessary",
        "bovendien": "also",
        "graag": "with pleasure",
        "daarna": "afterwards",
    },
    {
        "betalen": "to pay",
        "de/het soort": "kind of",
        "sluiten": "to close",
        "de punt": "full stop, point",
        "het punt": "item (abstract)",
        "raken": "to touch, to hit",
        "stellen": "to put (spoken)",
    },
]

core = [lesson for lesson in core if len(lesson) >= 15]
core_vocab = [lesson for lesson in core_vocab]

# Fiction

fiction = [
    {
        "de blik": "look, gaze",
        "Ze wendde haar blik af en roerde in het lege kopje": "She averted her gaze and stirred in the empty cup",
        "zwijgen": "to keep silent about",
        "We zwegen omdat het voor niemand zin had het rond te vertellen": "We kept silent because it didn't make sense for anyone to tell it round",
        "knikken": "to nod",
        "Ik knik tevreden en ga op de rand van het bed zitten": "I nod satisfied and go to sit on the edge of the bed",
        "schudden": "to shake",
        "De boom schudde in de wind": "The tree shook in the wind",
        "buigen (zich)": "to bend",
        "Hij boog zich en keek onder de tafel": "He bent and looked under the table",
        "glimlachen": "to smile",
        "Frederick wachtte een tel en glimlachte naar zijn fans": "Frederick waited a beat and smiled at his fans",
        "schrikken": "to be frightened",
        "Ik schrok toen ik zag hoe hij eraan toe was": "I was frightened when I saw the state of him",
        "Ik kon het al heel gauw met iedereen goed vinden": "I got along with everyone quickly",
    },
    {
        "omhoog": "up",
        "Ze kijkt omhoog naar de lucht alsof ze die voor het eerst ziet": "She looks up at the sky as though seeing it for the first time",
        "de stilte": "silence",
        "Er heerste een volkomen stilte": "There was complete silence",
        "voorzichtig": "careful",
        "Ik naderde de boederij met voorzichtige stappen en angst in het hart": "I approached the farmhouse with cautious steps and fear in my heart",
        "glijden": "to slide",
        "Ama laat zand door haar vingers glijden": "Ama lets sand slide through her fingers",
        "schreeuwen": "to shout",
        "Toen werd ze woest en ze schreeuwde dat er belangrijker dingen in het leven waren": "Then she became furious and she shouted that there were more important things in life",
        "werpen": "to throw",
        "Twee lampjes wierpen licht op het donkerbruine blad": "Two lamps cast light on the dark brown leaf",
        "dringen": "to push",
        "De honden stonden kwijlend om hun gevulde bakken te dringen": "The dogs were pressing drooling on their filled bowls",
        "Ik ga me haasten, de tijd dringt": "I'm going to hurry, time pushes on",
    },
    {
        "haast": "almost",
        "Ze kijkt me haast verontschuldigend aan": "She looks at me almost apologetically",
        "de traan": "tear",
        "Ze droogde de opgekomen tranen met de punt van haar schort": "She dried the risen tears with the point of her apron",
        "kruipen": "to crawl",
        "De spin kroop over de muur": "The spider crawled over the wall",
        "het gebaar": "gesture",
        "Ze maakte met haar hand het gebaar dat hij een beetje op moest schieten": "She made the gesture with her hand that he should hurry up a little",
        "de hemel": "sky, heaven",
        "De hemel boven me was blauw": "The sky above me was blue",
        "het lijf": "body",
        "Ik rukte het kledingstuk van haar lijf": "I tore the garment from her body",
        "het spoor": "track, trace",
        "Tot mijn verwondering toonde ze geen spoor van verwarring": "To my surprise she showed no trace of confusion",
        "Je zag er alleen de sporen van dieren": "You saw there only the tracks of animals",
    },
    {
        "verbergen": "to hide",
        "Ze verborg haar gezicht in haar handen": "She hid her face in her hands",
        "aarzelen": "to hesitate",
        "De knapen aarzelden om de snoepjes op te rapen": "The youngsters hesisitated to pick up the sweets",
        "kleden": "to dress",
        "Ik houd er niet van slordig gekleed te gaan": "I don't like to be dressed sloppily",
        "de geest": "mind, spirit",
        "De dromen hadden vluchtige beelden nagelaten in haar geest": "The dreams had left behind fleeting images in her mind",
        "branden": "to burn",
        "In de kamer brandden kaarsen": "Candles burned in the room",
        "overeind": "up",
        "Ariane kwam overeind uit haar stoel en streek haar kleren glad": "Ariane rose from her chair and smoothed out her clothes",
        "voortdurend": "continuous",
        "Veel van onze luisteraars klagen over voortdurende hoofdpijn": "Many of our listeners complain of continuous headaches",
        "Ze houden elkaar voortdurend in de gaten": "They keep watch on each other continuously",
    },
    {
        "smal": "narrow",
        "Het huis waarin wij woonden lag aan een smalle straat": "The house where we lived was in a narrow street",
        "schenken": "to donate",
        "De smidse schenk ik aan jou": "The forge I donate to you",
        "zuchten": "to sigh",
        "Ze zuchtte diep om de stroom gedachten te doorbreken": "She sighed deeply to break the stream of thoughts",
        "trillen": "to tremble, to shake",
        "Mijn benen trilden nog toen ik naar de badkamer liep": "My legs shook still when I walked to the bathroom",
        "bloot": "bare",
        "Ze voelt iets aan haar blote voeten": "She feels something on her bare feet",
        "zwaaien": "to wave",
        "De ziener zwaaide met zijn mantel over zijn uitgestoken arm": "The seer waved with his cloak over his outstretched arm",
        "opzij": "aside",
        "Ze ging opzij om hem door te laten": "She moved aside to let him through",
        "Mijn geloof staat haaks op de natuur": "My faith is at odds with nature",
    },
    {
        "de verte": "distance",
        "Ik staar naar de boederijen in de verte": "I stare at the farmhouses in the distance",
        "de hals": "neck",
        "Ik vond hem leuk met zijn blonde kuif en het gouden kettinkje om zijn hals": "I liked him with his blond crest and gold chain around his neck",
        "dun": "thin",
        "Saskia stond in haar dunne kimono te huiveren in de deuropening": "Saskia stood shivering in her thin kimono in the doorway",
        "het gezelschap": "company",
        "Hij blijft haar deze middag gezelschap houden": "He continues to keep her company this afternoon",
        "de klap": "blow",
        "Woedend had hij haar een klap om de oren gegeven": "Furious he had given her a blow around the ears",
        # 5
    },
]
fiction_vocab = [
    {
        "de blik": "look, gaze",
        "wenden (zich)": "to turn",
        "roeren": "to stir",
        "zwijgen": "to keep silent about",
        "knikken": "to nod",
        "schudden": "to shake",
        "buigen (zich)": "to bend",
        "glimlachen": "to smile",
        "de tel": "beat",
        "schrikken": "to be frightened",
    },
    {
        "omhoog": "up",
        "de stilte": "silence",
        "heersen": "to dominate",
        "volkomen": "completely",
        "voorzichtig": "careful",
        "glijden": "to slide",
        "schreeuwen": "to shout",
        "woest": "fierce",
        "werpen": "to throw",
        "dringen": "to push",
        "kwijlend": "drooling",
    },
    {
        "haast": "almost",
        "verontschuldigend": "apologetically",
        "de traan": "tear",
        "de schort": "apron",
        "kruipen": "to crawl",
        "het gebaar": "gesture",
        "de hemel": "sky, heaven",
        "het lijf": "body",
        "rukken": "to snatch, to tear",
        "het spoor": "track, trace",
        "de verwondering": "surprise",
        "de verwarring": "confusion",
    },
    {
        "verbergen": "to hide",
        "aarzelen": "to hesitate",
        "kleden": "to dress",
        "slordig": "sloppily",
        "de geest": "mind, spirit",
        "branden": "to burn",
        "overeind": "up",
        "voortdurend": "continuous",
    },
    {
        "smal": "narrow",
        "schenken": "to donate",
        "de smidse": "forge",
        "zuchten": "to sigh",
        "trillen": "to tremble, to shake",
        "bloot": "bare",
        "zwaaien": "to wave",
        "opzij": "aside",
        "haaks": "perpendicular",
    },
]

fiction = [lesson for lesson in fiction if len(lesson) >= 15]
fiction_vocab = [lesson for lesson in fiction_vocab]

# Newspapers

newspapers = [
    {
        "aldus": "thus, according to",
        "Een stormvloed spoelde de hele stad in een keer weg, aldus de overlevering": "A storm surge washed away the whole city in one go, according to legend",
        "de ploeg": "team",
        "De ploeg met de beste winnaarsmentaliteit zal zegeviernen": "The team with the best winner's mentality will prevail",
        "het beton": "concrete (n.)",
        "wegens": "because of",
        "Dekker kwam dit seizon wegens een knieblessure nauwelijks in actie": "Dekker was hardly in action this season because of a knee injury",
        "de wagen": "car",
        "Hij manoeuvreerde zijn wagen op de eerste startrij": "He manoeuvred his car onto the front row of the starting grid",
        "de woning": "house",
        "De rechten van de consument bij aankoop van een woning zijn belangrijk verbeterd": "Consumer rights when buying a home have improved significantly",
        "de strijd": "battle",
        "Zij heeft zich in het bijzonder gericht op de strijd voor de rechten van vrouwen en kinderen": "She has particularly focused on the battle for the rights of women and children",
        "momenteel": "currently",
        "De hypotheekrente is momenteel aan het stijgen": "Mortgage rates are currently climbing",
    },
    {
        "het ijzer": "iron (n.)",
        "de rechter": "judge",
        "De rechter besloot hem nog in voorarrest te houden": "The judge decided to keep him on remand still",
        "de reeks": "series",
        "In elk boek uit deze reeks staat achterin een kort interview met de auteur van de roman": "In each book in this series there is a short interview with the author of the novel in the back",
        "onlangs": "recently",
        "Wel realiseerde ik mij onlangs dat die concerten destijds vrij kort waren": "I did realise recently that those concerts at the time were quite short",
        "het bestuur": "board",
        "Moet iedere beslissing worden voorgelegd aan het bestuur?": "Must every decision be submitted to the board?",
        "de winst": "profit",
        "De winst is hoger dan analisten hadden verwacht": "The profit is higher than analysts had expected",
        "de steun": "support",
        "De zangeres vertelt veel steun aan haar familie te hebben": "The singer says she has a lot of support from her family",
        "kosten": "costs",
        "De wet staat dan toe die kosten als aftrekpost op te voeren in de aangifte inkomstenbelasting": "The law then allows those expenses to be deducted in the income tax return",
    },
    {
        "betonnen": "concrete (adj.)",
        "de verkiezing": "election",
        "Hij doet nog wel mee als lijstduwer aan de verkiezingen": "He does still participate as a list pusher in the elections",
        "veroordelen": "to condemn",
        "De man is deze week tot twee jaar gevangenisstraf veroordeeld": "This week the man was condemned to two years in prison",
        "de bestuurder": "manager",
        "Bestuurders die niet goed hebben gefunctioneerd moeten geen gouden handdruk krijgen": "Managers who have not performed well must get no golden handshake",
        "aankondigen": "to announce",
        "Het kabinet kondigt die maatregel aan op Prinsjesdag": "The cabinet announces that measure on Prince's day",
        "de bewoner": "occupant, resident",
        "De huizen van de bewoners worden door middel van lijnen op een plattegrond aangegeven": "Residents' houses are indicated by lines on a map",
        "de dader": "perpetrator, offender",
        "Aan de hand van verklaringen kon de politie een signalement van de dader opstellen": "Based on statements the police were able to draw up a description of the perpetrator",
        "stelen": "to steal",
        "Dieven hebben de aanhangwagens en opleggers gestolen": "Thieves have stolen the trailers and semi-trailers",
    },
    {"ijzeren": "iron (adj.)"},
    {"hout": "wood"},
    {"houten": "wooden"},
]
newspapers_vocab = [
    {
        "aldus": "thus, according to",
        "spoelen": "to wash",
        "de overlevering": "legend, tradition",
        "de ploeg": "team",
        "zegeviernen": "to prevail",
        "het beton": "concrete (n.)",
        "wegens": "because of",
        "nauwelijks": "rarely",
        "de wagen": "car",
        "de woning": "house",
        "de strijd": "battle",
        "momenteel": "currently",
        "de hypotheekrente": "mortgage rate",
        "stijgen": "to rise",
    },
    {
        "het ijzer": "iron (n.)",
        "de rechter": "judge",
        "de reeks": "series",
        "onlangs": "recently",
        "destijds": "at the time",
        "het bestuur": "board",
        "voorleggen": "to submit",
        "de winst": "profit",
        "de steun": "support",
        "kosten": "costs",
        "de wet": "law",
    },
    {
        "betonnen": "concrete (adj.)",
        "de verkiezing": "election",
        "veroordelen": "to condemn",
        "de bestuurder": "manager",
        "aankondigen": "to announce",
        "de bewoner": "occupant, resident",
        "de dader": "perpetrator, offender",
        "de signalement": "description",
        "opstellen": "to draw up",
        "de verklaring": "statement",
        "stelen": "to steal",
    },
]

newspapers = [lesson for lesson in newspapers if len(lesson) >= 15]
newspapers_vocab = [lesson for lesson in newspapers_vocab]

# Spoken

spoken = [
    {
        "het tijdstip": "(point of/in) time",
        "naartoe": "to there",
        "Ik ben van plan daar vrijdag naartoe te gaan": "I plan to go there on Friday",
        "hu": "ugh",
        "Hu, wat een moeilijk woord": "Ugh, what a difficult word",
        "eventjes": "quickly",
        "Ik dacht toch nog eventjes in te pikken op de vorige les": "Even so I thought I would quickly connect to the last lesson",
        "hartstikke": "terribly",
        "Dat is hartstikke fijn voor dat kind": "That is heartening for that child",
        "ontzettend": "tremendous, terrible",
        "Wij hadden ontzettende last van jetlag": "We had terrible jetlag",
        "oei": "oops",
        "Jan denkt oei, ik moet haar nog even feliciteren": "Jan thinks oops, I must congratulate her",
        "sowieso": "anyway",
        "Ze moet daar sowieso terug naartoe": "She has to go back there anyway",
    },
    {
        "verschrikkelijk": "terrible",
        "Het was een verschrikkelijke wedstrijd": "It was a terrible match",
        "enfin": "in short, anyway",
        "Enfin, we gaan mekaar in ieder geval zien rond half tien": "Anyway, we are going to see each other around half past nine in any case",
        "gauw": "soon, quickly",
        "Daan haalt gauw zijn schrijft uit zijn tas": "Daan quickly gets his writing from his bag",
        "het spul": "stuff, things",
        "William gaat met zijn vader naar huis om wat spullen op te halen": "William goes home with his father to fetch some things",
        "anderhalf": "one and a half",
        "Hij heeft deze voormiddag anderhalf uur geslapen": "He slept for an hour and a half this morning",
        "hoezo": "why",
        "Dat weet ik niet, hoezo?": "I didn't know that, why?",
        "de heleboel": "a lot",
        "Er lopen hier een heleboel volwassenen rond, maar ik weet niet wie het allemaal zijn": "A lot of adults walk around here, but I don't know who they all are",
        "het tijdperk": "era",
    },
    {
        "net": "neat, tidy",
        "De kamer was heel proper, heel net, maar sober": "The room was very tidy, very neat, but plain",
        "tevoren": "before",
        "We moeten twee uur van tevoren inchecken": "We have to check in two hours before",
        "verbreken": "to break up/off",
        "De verbinding wordt over dertig seconden verbroken": "The connection will be broken off in thirty seconds",
        "alhoewel": "although",
        "Ik vind dat zelf niet zo'n probleem, alhoewel ik het wel jammer vind": "I don't find that such a problem myself, although I think it's a shame",
        "opschrijven": "to write down",
        "Wat hij zegt, moet je niet allemaal opschrijven": "You musn't write down all of what he is saying",
        "rap": "fast, quickly (FL)",
        "Dan is dat rap gedaan": "Then that's quickly done",
        "voormalig": "former",
        "tijdelijk": "temporarily",
        "voortdurend": "continuous",
    },
    {
        "gelijk": "just as",
        "Het was daar helemaal bewolkt gelijk hier": "It was completely cloudy there just like here",
        "dadelijk": "immediately",
        "Dus als je wil kan je er dadelijk al even naar kijken": "So if you want you can immediately have a look at it",
        "benieuwd": "curious",
        "Eigenlijk ben ik daar wel benieuwd naar": "Actually I am curious about that",
        "daarnet": "just (now)",
        "U zei daarnet ook dat u van sporten houdt": "You also said just now that you love sports",
        "lesgeven": "to teach",
        "We hebben twee leerkrachten Nederlands die één uur per week lesgeven aan anderstaligen": "We have two Dutch teachers who teach one hour per week to non-native speakers",
        "eraf": "off",
        "Nu wil ik mijn haar eraf": "Now I want my hair off",
        "najaar": "autumn",
        "namiddag": "late afternoon",
        "eeuwigheid": "eternity",
    },
    {
        "huidig": "current",
        "voorlopig": "provisional",
        "zat": "plenty",
        "Ilse is rijk zat": "Ilse is plenty rich",
        "tussendoor": "in between",
        "Dat fietsen was maar even tussendoor": "That cycling was just in between",
        "erachter": "behind (it/them)",
        "Je moet dit gewoon afsluiten, punt erachter": "You just have to shut this down, full stop",
        "Hoe kom je erachter of dat waar is?": "How do you find out if that's true?",
        "uitzoeken": "to select, to choose",
        "Straks gaat hij samen met oma ontbijten en mag hij uitzoeken wat hij lekker vindt": "Later he will have breakfast with grandma and he can choose what he likes",
        "stage": "internship",
        "Zij loopt stage bij de kleuters": "She is doing an internship with the pre-schoolers",
        "tamelijk": "rather",
        "Ze bleven tamelijk lang weg": "They stayed away for rather a long time",
    },
    {
        "voorjaar": "spring",
        "toenmalig": "former, then",
        "daarachter": "behind it, behind them",
        "Daarachter begint het moeras": "Behind it starts the swamp",
        "wreed": "cruel",
        "Het was een tamelijk wrede wetgeving": "It was a rather cruel piece of legislation",
        "voorlezen": "to read aloud",
        "Ik heb bijna een heel boek voorgelezen": "I have read almost an entire book aloud",
        "kletsen": "to chat",
        "Sommige mensen stonden alleen maar te kletsen, die letten helemaal niet op": "Some people stood around chatting, not paying attention at all",
        "daarstraks": "just now",
        "Wat heb ik daarstraks op de radio gehoord?": "What have I just heard on the radio?",
        "inleveren": "to hand in, to sacrifice",
        "We moesten meteen onze paspoorten inleveren": "We had to immediately hand in our passports",
        "Moeten we koopkracht inleveren in ruil voor kwaliteit?": "Should we sacrifice purchasing power in exchange for quality?",
    },
    {
        "hedendaags": "contemporary",
        "uiteindelijk": "final",
        "langdurig": "prolonged",
        "ho": "stop",
        "Ik had echt zoiets van ho, dit kun je niet maken": "I was really like stop, you can't do this",
        "diegene": "he, she, those who",
        "Diegene die wint is dan toch de beste": "He who wins is still the best",
        "tof": "great",
        "Ga je nog wat toffe dingen doen in de vakantie?": "Are you going to do some great things in the holiday?",
        "eruitzien": "to look (like)",
        "Ik weet niet hoe dat beest eruitziet": "I don't know what that animal looks like",
        "omheen": "around",
        "Het is een soort vuur en er dansen figuren omheen": "It is a kind of fire and figures dance around it",
        "daarboven": "above it",
        "Ze zijn een parkeergarage aan het bouwen en daarboven komen winkels": "They are building a parking garage and above it will be shops",
    },
    {
        "heden": "today",
        "de rotzooi": "junk, mess",
        "Ik ben intussen even de rotzooi aan het opruimen": "I am in the meantime just clearing up the mess",
        "vanachter": "from behind",
        "Hij stond op vanachter zijn bureau en deed de deur open": "He stood up from behind his desk and opened the door",
        "de rugzak": "backpack",
        "De zaklamp deed hij in de zwarte rugzak": "He put the torch in the black backpack",
        "overheen": "across, over",
        "Je kunt er een tafelkleedje overheen leggen": "You can put a table cloth over it",
        "erom": "about it",
        "Klaas lacht erom": "Klaas laughs about it",
        "de file": "traffic jam",
        "Hou tijdens de spitsuren rekening met lange files": "Keep in mind long traffic jams during rush hours",
        "gelukken": "to succeed",
        "Het plan is gelukt": "The plan succeeded",
    },
    {
        "verleden": "past, last",
        "hartelijk": "warm",
        "Doe Riet de hartelijke groeten van mee": "Give Riet my warm wishes",
        "gaaf": "great",
        "Hij had wel gedacht dat ze het een gaaf idee zouden vinden": "He did think that they would find it a great idea",
        "langzamerhand": "gradually",
        "De mist verdwijnt langzamerhand": "The fog disappears gradually",
        "ertussen": "in between",
        "Hij had grote stevige voortanden met kleine spleetjes ertussen": "He had big solid front teeth with small slits between them",
        "langskomen": "to pass by, to come round",
        "Hij zei je moet morgen maar langskomen of zo": "He said you should come by tomorrow or so",
        "eronder": "below",
        "Bob heeft alleen maar de krik eronder gezet": "Bob only put the jack below it",
        "nakijken": "to check",
        "Ik heb het niet gezien, maar ik zal het nog eens nakijken": "I have not seen it, but I will check again",
    },
    {
        "ernaast": "next to it, beside it",
        "Er staat een oude schrijfmachine en ernaast ligt een stapel wit papier": "There is an old typewriter and next to it is a pile of white paper",
        "weeral": "again",
        "Vaderdag ligt weeral vergeten achter de rug": "Father's day is already behind us",
        "plezierig": "pleasant",
        "Ik vind dat toch zo plezierig": "I find that so pleasant",
        "klaarmaken": "to prepare",
        "Anja heeft lekkere chocolademelk klaargemaakt": "Anja prepared delicious chocolate milk",
        "eromheen": "around it",
        "Ze draagt een gekleurd pak met een grote rode strik eromheen": "She wears a coloured suit with a large red bow around it",
        "opsturen": "to send",
        "Ik heb nog een brief opgestuurd naar u": "I have just sent a letter to you",
        "de goesting": "fancy (FL)",
        "Delphine had geen goesting om uit te gaan": "Delphine did not fancy going out",
        "de zin": "fancy (NL)",
    },
]
spoken_vocab = []

spoken = [lesson for lesson in spoken if len(lesson) >= 15]
spoken_vocab = [lesson for lesson in spoken_vocab]

# Web

web = [
    {
        "de gemeente": "municipality",
        "De provincies en de gemeenten hebben op tal van plaatsen scholen opgericht": "The provinces and municipalities have founded schools in numerous places",
        "huidig": "current",
        "De huidige situatie kan sterk verbeterd worden": "The current situation can be greatly improved",
        "de bron": "source",
        "Dagboeken zijn een belangrijke bron voor historisch onderzoek": "Journals are an important source for historical research",
        "de regering": "government (ministers)",
        "De invloed die burgers kunnen uitoefenen op hun regering is gierig": "The influence those citizens can exert on their government is minimal",
        "ene": "a, one",
        "De ene week werken we wat harder dan de andere": "The one week we work somewhat harder than the other",
        "de oppervlakte": "surface",
        "De oppervlakte van een voetbalveld is minimaal 4050 vierkante meter": "The surface of a football field is at least 4050 square metres",
        "de cijfer": "figure, number, mark",
        "Die cijfers geven een vertekend beeld": "Those figures give a distorted picture",
        "Leerlingen die goede cijfers halen, verdienen straks vrije uren": "Pupils who get good marks earn free hours later",
    },
    {
        "de bevolking": "population",
        "Hij vertegenwoordigt een grote laag van de huidige Vlaamse bevolking": "He represents a large layer of the current Flemish population",
        "divers": "various",
        "Al in zijn middelbare schooltijd had hij diverse gedichten geschreven": "He had written various poems already in his middle school",
        "indien": "if",
        "We gaan na hoe de resultaten wijzigen indien een correctie wordt ingebound": "We examine how the results change if a correction is made",
        "aangezien": "since",
        "De schrik sloeg me om het hart aangezien ik daar een heel ander idee bij had": "The shock struck me to the core since I had a very different idea about it",
        "oprichten": "to establish, to found",
        "Stichtingen worden vooral voor goede doelen opgericht": "Foundations are established primarily for charitable purposes",
        "verenigen (zich)": "to unite",
        "Individuen kunnen zich verenigen en gezamenlijke belangen verdedigen": "Individuals can unite and defend common interests",
        "tevens": "also",
        "De diefstal van de autosleutels betekende tevens de diefstal van de auto zelf": "The theft of the car keys also meant the theft of the car itself",
        # "": "",
    },
    {
        "oorspronkelijk": "original",
        "De oorspronkelijke bewoners van Austalië heten Aboriginals": "The original occupants of Australia are called Aboriginals",
        "waaronder": "including",
        "De president heeft uitgebreide bevoegdheden, waaronder ministeriële en diplomatieke benoemingen": "The president has extensive powers, inlcuding ministerial and diplomatic appointments",
        "baseren": "to base (on)",
        "Het eindcijfer is gebaseerd op twee proefwerken en een mondelinge presentatie": "The final mark is based on two test papers and an oral presentation",
        "vervangen": "to replace",
        "Na de rust werd hij vervangen door een extra spits": "After halftime he was replaced by an additional striker",
        "bedragen": "to amount (to)",
        "Pensioenen bedragen 70% van het gemiddelde salaris": "Pensions amount to 70% of the average salary",
        "voornamelijk": "mainly",
        "Het onderwijssysteem is kwalitatief hoogwaardig en wordt voornamelijk publiek gefinancierd": "The education system is high quality and mainly publicly funded",
        # 3*""
    },
]
web_vocab = [
    {
        "de gemeente": "municipality",
        "huidig": "current",
        "de bron": "source",
        "de regering": "government (ministers)",
        "de invloed": "influence",
        "uitoefenen": "to exert",
        "gierig": "stingy",
        "ene": "a, one",
        "de oppervlakte": "surface",
        "de cijfer": "figure, number, mark",
        "vertekend": "distorted",
    }
]

web = [lesson for lesson in web if len(lesson) >= 15]
web_vocab = [lesson for lesson in web_vocab]

# General

general = [
    {
        "echter": "however",
        "We zien echter weinig van de buurt": "We see little in the neighbourhood however",
        "immers": "indeed",
        "Wijsheid en stilte zijn immers eeuwig en altijd met elkaar verbonden": "Wisdom and silence are indeed eternal and always connected with each other",
        "de overheid": "government (administration)",
        "De bezuinigingen van de overheid werden morrend geaccepteerd": "The government cutbacks were morosely accepted",
        "behoren": "to belong",
        "Pas als er duidelijkheid bestaat, behoort dat weer tot de mogelijkheden": "Only when there is clarity, will that be a possibility again",
        "intussen": "meanwhile",
        "Een verse regenzone komt intussen van het westen uit dichterbij": "Meanwhile, a fresh rain zone approaches from the west",
        "de raad": "advice",
        "Zij geeft raad aan mensen die financiële problemen hebben": "She gives advice to people with financial problems",
        "liefst": "preferably",
        "willen het liefst": "to prefer",
        "Mijn man wil het liefst kamperen en ik wil het liefst in een huisje": "My husband prefers camping and I prefer a cottage",
    },
    {
        "uitvoeren": "to perform",
        "Een beperkt aantal chirurgen kan deze handelingen uitvoeren": "A limited number of surgeons can perform these operations",
        "het niveau": "level",
        "Er is onderwijs voor jongeren op alle niveaus": "There is education for young people at all levels",
        "bedoelen": "to intend",
        "Ik begreep nooit zo goed wat hij daarmee bedoelde": "I never understood well what he meant with it",
        "beperken": "to limit",
        "Hierdoor wordt de schade mogelijk beperkt": "This potentially limits the damage",
        "treden": "to step",
        "Hij trad naar voren": "He stepped forward",
        "bevestigen": "to confirm",
        "Een getuige bevestigt dat de auto te hard het kruispunt opreed": "A witness confirms that the car was speeding into the junction",
        "weigeren": "to refuse",
        "Hij weigerde in te zien dat ze kansloos waren": "He refused to see that they were hopeless",
        "aanwezig": "present",
    },
    {
        "de uitspraak": "statement",
        "Haar uitspraken vielen niet in goede aarde": "Her statements did not fall on good ground",
        "de druk": "pressure",
        "China staat onder sterke druk van de internationale gemeenschap": "China is under strong pressure from the international community",
        "veroorzaken": "to cause",
        "Volgens hem heeft de lekkage geen brand veroorzaakt": "According to him the leakage did not cause a fire",
        "de klant": "customer",
        "De leverancier nam met tranen in de ogen afschied van zijn beste klant": "The supplier took leave of his best customer with tears in his eyes",
        "de ontwikkeling": "development",
        "In ons vakgebied hebben zich de laatste jaren belangrijke ontwikkelingen voorgedaan": "In our field there have been important developments in recent years",
        "bevinden (zich)": "to find",
        "Onder een laag klei van 700 meter bevindt zich een laag zout van 200 meter diep": "Under a layer of clay of 700 metres is found a layer of salt 200 metres deep",
        "de poging": "attempt",
        "Hij deed nog een poging om te winnen": "He made another attempt to win",
        "knap": "handsome",
    },
    {
        "verantwoordelijk": "responsible",
        "De brief bleek fataal te zijn voor de verantwoordelijke bestuursleden": "The letter proved fatal for the responsible board members",
        "minstens": "at least",
        "Hij is minstens nog een half hoofd groter dan zij": "He is at least another half a head taller than her",
        "beweren": "to claim",
        "Ik beweer dat het overleg niet heeft plaatsgevonden": "I claim that the consultation did not take place",
        "de fout": "error",
        "De ene fout maakt de ander niet goed": "One error does not make up for another",
        "dwingen": "to force",
        "Desnoods moest ze hem dwingen vrienden uit te nodigen": "If necessary she had to force him to invite friends over",
        "de leiding": "leadership",
        "Onder zijn leiding werd het land een democratie": "Under his leadership the land was a democracy",
        "steunen": "to support",
        "Zij steunde hem in alles wat hij deed": "She supported him in all that he did",
        "recht": "straight",
    },
    {
        "dalen": "to go down",
        "Vandaag daalt de prijs voor benzine en stookolie": "Today the price of petrol and heating oil goes down",
        "dom": "stupid",
        "de omstandigheid": "circumstance",
        "Het is nooit duidelijk geworden onder welke omstandigheden hij is gestorven": "It has never become clear under what circumstances he died",
        "reeds": "already",
        "Wij lopen hier reeds tientallen jaar rond": "We've been around here for decades",
        "bevatten": "to contain",
        "Het archief bevat ook vrij recente documenten": "The archive also contains fairly recent documents",
        "de praktijk": "practice",
        "De praktijk is vaak heel anders dan de theorie": "The practice is often very different to the theory",
        "herstellen": "to recover",
        "Hij herstelde van zijn val": "He recovered from his fall",
        "de maatschappij": "society",
        "Onze maatschappij is drastisch veranderd": "Our society has changed drastically",
    },
    {
        "vals": "false",
        "het proces": "trial",
        "Het hele proces verliep voorspoedig": "The whole trial went smoothly",
        "de verklaring": "statement",
        "Heb jij een verklaring voor zijn gedrag?": "Do you have an explanation for his behaviour?",
    },
    # {
    #     "lelijk": "ugly",
    #     "krom": "crooked",
    #     "scheef": "crooked",
    #     "slim": "clever",
    #     "eerlijk": "honest, fair",
    #     "slordig": "untidy",
    #     "terecht":"deserved",
    #     "waarschijnlijk":"probably",
    #     "gelijk":"equal",
    #     "rustig":"quiet",
    #     "voldoende":"sufficient"
    #   "bewust":"conscious",
    #   "gerust":"calm",
    #   "afhankelijk":"dependent",
    #   "handig":"handy",
    #   "schuldig":"guilty",
    #   "aangenaam":"pleasant",
    #   "gelovig":"faithful",
    #   "geduldig":"patient"
    #   "ongemakkelijk":"uncomfortable",
    #   "onterecht":"undeserved",
    #   "onwaarschijnlijk":"unlikely",
    #   "ongelijk":"unequal",
    #   "onrustig":"restless",
    #   "onvoldoende":"insufficient"
    #   "onbewust":"unconscious",
    #   "ongerust":"anxious",
    #   "ofanhankelijk":"independent",
    #   "onhandig": "awkward",
    #   "onschuldig":"innocent",
    #   "onaangenaam":"unpleasant",
    #   "ongelovig":"faithless",
    #   "ongeduldig":"impatient"
    # },
]
general_vocab = []

general = [lesson for lesson in general if len(lesson) >= 15]
general_vocab = [lesson for lesson in general_vocab]

proper_nouns_eng = [
    "Amsterdam",
    "Lena",
    "Laura",
    "Betty",
    "Els",
    "Jan",
    "Daan",
    "William",
    "Ilse",
    "August",
    "April",
    "March",
    "December",
    "Friday",
    "Dutch",
    "Klaas",
    "Riet",
    "Anja",
    "Flemish",
    "Prince's",
    "Aboriginals",
    "Australia",
]

proper_nouns_ned = [
    "Amsterdam",
    "Lena",
    "Laura",
    "Betty",
    "Els",
    "Jan",
    "Daan",
    "William",
    "Ilse",
    "Klaas",
    "Riet",
    "Anja",
    "Vlaamse",
    "Nederlands",
    "Prinsjesdag",
    "Aboriginals",
    "Australië",
]


available_lessons = {
    "core": [core, core_vocab],
    "fiction": [fiction, fiction_vocab],
    "newspapers": [newspapers, newspapers_vocab],
    "spoken": [spoken, spoken_vocab],
    "web": [web, web_vocab],
    "general": [general, general_vocab],
}


alternatives = {
    "All the information about camping is on the website": "All the information about camping can be found on the website",
    "Na enkele seconden hoorde ik de auto ook": "Na enkele seconden hoorde ik ook de auto",
    "One of our friends is staying somewhere else": "One of our friends stays somewhere else",
    "We stand in front of the hotel door": "We stand in front of the door of the hotel",
    "Children were playing on the square near the church": "On the square near the church children were playing",
    "He made a fast motion": "He made a quick motion",
    "He repaired her broken bicycle": [
        "He repaired her broken bike",
        "He fixed her broken bike",
        "He fixed her broken bicycle",
    ],
    "He decided to go alone": "He has decided to go alone",
    "He was too quick for me": "He beat me to it",
    "He put that it is important to work together": "He stated that it is important to work together",
    "Everything was dark and silent near us in the village": "In the village near us everything was dark and silent",
    "The shopfront had stood empty for some time after the bankruptcy of the previous owner": [
        "The shopfront stood empty for some time after the bankruptcy of the previous owner",
        "The shopfront was standing empty for some time after the bankruptcy of the previous owner",
    ],
    "You also need roasted rice for this recipe": "For this recipe you  also need roasted rice",
    "Betty did not feel completely at ease": [
        "Betty did not feel completely at her ease",
        "Betty didn't feel completely at ease",
    ],
    "Els hesitates because she doesn't actually want to move": "Els hesitates because she doesn't actually want to move house",
    "Young people must sooner learn to cooperate than compete with each other": [
        "Young people should learn to cooperate rather than compete with each other",
        "Young people should learn to work together rather than compete with each other",
    ],
    "A few yellowed greetings cards are on the bedside table": "On the bedside table stand a few yellowed greetings cards",
    "Op het pleintje bij de kerk waren kinderen aan het spelen": "Kinderen waren op het pleintje bij de kerk aan het spelen",
    "Alle informatie over de camping vind je op de website": "Je vind alle informatie over de camping op de website",
    "Het examen aardrijkskunde was volgens de leerlingen te moeilijk": "Het examen aardrijkskunde was te moeilijk volgens de leerlingen",
    "Bij ons in het dorp was alles donker en stil": "Alles was donker en stil bij ons in het dorp",
    "Voor dit gerecht heeft u ook geroosterde rijst nodig": [
        "U heeft ook geroosterde rijst voor dit gerecht nodig",
        "Voor dit gerecht hebt je ook geroosterde rijst nodig",
        "Je hebt ook geroosterde rijst voor dit gerecht nodig",
    ],
    "Op het nachtkastje staan een paar vergeelde wenskkaarten": "Een paar vergeelde wenskkaarten staan op het nachtkastje",
    "Dit evenement trekt ieder jaar veel bezoekers": "Dit evenement trekt veel bezoekers ieder jaar",
    "Some people whistle the whole day": "Some people whistle all day",
    "Sometimes things don't go your way": [
        "Sometimes things don't go the way you want",
        "Sometimes things don't go as you want",
    ],
    "A start was made with reforms": ["Reforms were started", "Reforms were intiated"],
    "We were learning and our parents and teachers were pleased to see that": "We were learning and that pleased our parents and teachers",
    "The light wintery weather seems set to continue the coming weekend and probably beyond": "The light wintery weather seems set to continue the coming weekend and probably also afterwards",
    "The town also pays the energy bill": "The city also pays the energy bill",
    "The sentence finishes with a full stop": "The sentence ends with a full stop",
    "She took care in bed that her feet did not touch his body": [
        "In bed she took care that her feet did not touch his body",
        "She took care that her feet did not touch his body in bed",
    ],
    "A reason for the divorce was not given": "No reason was given for the divorce",
    "William goes home with his father to fetch some things": "William goes home with his father to get some things",
    "Daan quickly gets his writing from his bag": "Daan gets his writing quickly from his bag",
    "I found another way to help you": "I have found another way to help you",
    "The connection will be broken off in thirty seconds": "The connection will be disconnected in thirty seconds",
    "Even so I thought I would quickly come back to the last lesson": "Even so I thought I would quickly return to the last lesson",
    "Behind it starts the swamp": [
        "Behind it the swamp starts",
        "Behind it the swamp begins",
    ],
    "I have read almost an entire book aloud": [
        "I have read almost a whole book aloud",
        "I have almost read a whole book aloud",
        "I have read almost a whole book out loud",
    ],
    "This is evident from a first report from the research agency": "This is evident from a first report from the research institute",
    "Ze was zeer verzwakt en woog nog 46 kilo": [
        "Ze was heel verzwakt en woog nog 46 kilo",
        "Ze was erg verzwakt en woog nog 46 kilo",
    ],
    "very (written)": "very",
    "to put (spoken)": "to put",
    "to put (down)": "to put",
    "Dan is dat rap gedaan": "Dan is dat snel gedaan",
    "Should we sacrifice purchasing power in exchange for quality?": "Must we sacrifice purchasing power in exchange for quality?",
    "He who wins is still the best": "The one who wins is still the best",
    "You can put a table cloth over it": "You can put a tablecloth over it",
    "Keep in mind long traffic jams during rush hours": "Expect long traffic jams during rush hours",
    "He did think that they would find it a great idea": "He thought that they would find it a great idea",
    "Ik heb nog een brief opgestuurd naar u": "Ik heb nog een brief opgestuurd naar jou",
    "fancy (FL)": "fancy",
    "fancy (NL)": "fancy",
    "Delphine had geen goesting om uit te gaan": "Delphine had geen zin om uit te gaan",
    "In bed zorgde ze ervoor dat haar voeten zijn lichaam niet raakten": "In bed zorgde zij ervoor dat haar voeten zijn lichaam niet raakten",
    "The tall girl could reach the top shelf": "The tall girl could reach the highest shelf",
    "It sounded like a decision that had long been considered": " It sounded like a decision which was long considered",
    "Hij ging even een biertje drinken in het cafe": [
        "Hij ging even weg om bier te drinken in het cafe",
        "Hij ging even bier drinken in het cafe",
    ],
    "Het was daar helemaal bewolkt gelijk hier": "Daar was het helemaal bewolkt gelijk hier",
    "He had written various poems already in his middle school": "Already in his middle school he had written various poems",
    "Pupils who get good marks earn free hours later": "Pupils who get good grades earn free hours later",
    "Leadership usually comes into its own only in moments of crisis": "Leadership usually only comes into it's own in times of crisis",
    "We have to check in two hours before": "We must check in two hours before",
    "Then that's quickly done": "Then that is quickly done",
    "Two lamps cast light on the dark brown leaf": "Two lamps threw light on the dark brown leaf",
    "I'm going to hurry, time pushes on": [
        "I'm going to hurry, time is short",
        "I'm going to hurry, time is running out",
    ],
    "iron (adj)": "iron",
    "concrete (adj)": "concrete",
    "A storm surge washed away the whole city in one go, according to legend": [
        "A storm surge washed away the whole town in one go, according to legend",
        "A storm surge washed the whole town away in one go, according to legend",
        "A storm surge washed the whole city away in one go, according to legend",
    ],
    "The forge I donate to you": "I donate the forge to you",
    "My legs shook still when I walked to the bathroom": [
        "My legs still shook when I walked to the bathroom",
        "My legs were still shaking when I walked to the bathroom",
    ],
    "They keep watch on each other continuously": "They are continuously watching each other",
    "Anyway, we are going to see each other around half past nine in any case": "Anyway we are going to see each other around half past nine in any case",
    "Consumer rights when buying a home have improved significantly": "Consumer rights when buying a home have significantly improved",
    "So if you want you can immediately have a look at it": [
        "So if you want you can look at it immediately",
        "So if you want you can have a look at it immediately",
    ],
    "Daarmee was ze een seconde sneller dan haar oude toptijd": "Daarmee was zij een seconde sneller dan haar oude toptijd",
    "In each book in this series there is a short interview with the author of the novel in the back": "In each book from this series there is a short interview with the authour of the novel in the back",
    "I did realise recently that those concerts at the time were quite short": "I did realise recently that those concerts were quite short at the time",
    "You musn't write down all of what he is saying": "You musn't write down everything that he says",
    "She gives advice to people with financial problems": "She gives advice to people who have financial problems",
    "Only when there is clarity, will that be a possibility again": "Only when there is clarity will that be a possibility again",
    "Meanwhile, a fresh rain zone approaches from the west": "Meanwhile a fresh rain zone approaches from the west",
    "government (administration)": "government",
    "government (ministers)": "government",
    "Managers who have not performed well must get no golden handshake": "Managers who have not performed well should get no golden handshake",
    "to prepare": "to get ready",
    "(point of/in) time": "point in time",
    "(point of/in) time": "point of time",
    "William goes home with his father to fetch some things": "William goes home with his father to fetch some stuff",
    "The provinces and municipalities have founded schools in numerous places": "The provinces and the municipalities have founded schools in numerous places",
    "A limited number of surgeons can perform these operations": "A limited number of surgeons are able to perform these operations",
    "We kept silent because it didn't make sense for anyone to tell it round": "We stayed silent because it didn't make sense for anyone to tell it round",
    "Daan quickly gets his writing from his bag": "Daan quickly gets his writing out of his bag",
    "Even so I thought I would quickly connect to the last lesson": "Even so I thought that I would quickly connect to the last lesson",
    "Dekker was hardly in action this season because of a knee injury": "Dekker was rarely in action this season because of a knee injury",
    "It sounded like a decision that had long been considered": "It sounded like a decision which was long thought over",
    "She looks up at the sky as though seeing it for the first time": "She looks up at the sky as if seeing it for the first time",
    "careful": "cautious",
    "In each book in this series there is a short interview with the author of the novel in the back": "In each book from this series there is a short interview with the author of the novel in the back",
    "to keep silent about": ["to stay silent", "to keep silent"],
    "I got along with everyone quickly": "I got on quickly with everyone",
}
